server:
  host: "0.0.0.0"
  port: 3000
  workers: 4

database:
  url: "postgres://postgres:password@localhost:5432/marketplace"
  max_connections: 10
  connect_timeout: 30

jwt:
  secret: "your-secret-key-change-this-in-production"
  access_token_expires_in: 3600  # 1 hour
  refresh_token_expires_in: 604800  # 7 days

storage:
  upload_path: "./uploads"
  max_file_size: 104857600  # 100MB
  use_cdn: false
  cdn_base_url: "https://cdn.geektools.dev"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "https://geektools.dev"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "Accept"
    - "Origin"
    - "X-Requested-With"