[package]
name = "geektools"
version = "0.2.2"
edition = "2024"

[dependencies]
reqwest     = { version = "0.12.20", default-features = false, features = ["blocking", "rustls-tls"] }
serde_json = "1.0"
once_cell = "1.18.0"
rust-embed = { version = "8", features = ["include-exclude"] }
rand = "0.9.1"
