[profile.release]
opt-level       = "z"
lto             = true
codegen-units   = 1
strip           = "symbols"
panic           = "abort"


[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
ar     = "x86_64-linux-musl-ar"
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
ar     = "aarch64-linux-musl-ar"
rustflags = ["-C", "target-feature=+crt-static"]